name: StreetLightZ
version: 1.0
main: me.rigor789.StreetLightZ.StreetLightZ
author: rigor789
permissions:
    streetlightz.edit:
        description: Acces to streetlightz edit command
        default: op
commands:
 StreetLightZ:
   description: StreetLightZ base command!
   aliases: [sl]
   permissions: 'streetlightz.edit'
